### ISSUE TITLE
App crashes on loading certain conversations

### ISSUE THREAD

**Issue by bvija03** [twilio/twilio-conversations-demo-ios-swift#17]
<img width="1520" alt="Screen Shot 2023-10-09 at 3 53 54 PM" src="https://github.com/twilio/twilio-conversations-demo-ios-swift/assets/76533015/1e8dd158-8f41-42a5-be10-ed459582425c">
<img width="1494" alt="Screen Shot 2023-10-09 at 4 26 08 PM" src="https://github.com/twilio/twilio-conversations-demo-ios-swift/assets/76533015/baab94cb-14e7-4789-8dec-ec22a4c19724">

Using the app loading certain conversations or replying to them caused the app to crash.

**Comment by bvija03** [comment]
I removed it. It was a test dummy URL. It will be disabled soon.

**Comment by berkus** [comment]
Ok, we don't plan to fix this immediately, but this should be a fairly easy change to do it yourself.

**Comment by hcossio** [comment]
just make the participantSid attribute as Optional. It is located in Models -> CoreData -> ConversationsApp -> Entities (PersistentMessageDataItem) click on participantSid and on the right panel click on Optional. Save. Run.
